#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yc () {
    setting="${1}"
    value="${2}"
    yabai -m config ${setting} ${value}
}

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# focus_window () {
#     SPACE_NAME=$(yabai -m query --spaces --space | jq ".label")
#     WINDOW_ID=$(yabai -m query --windows --space | jq ".[] | select (.app=${SPACE_NAME}).id")
#     yabai -m window --focus "${WINDOW_ID}"
# }
#
# # focus window after active space changes
# yabai -m signal --add event=space_changed action="focus_window"

# focus window after active display changes
yabai -m signal --add event=display_changed action="focus_window"

# Spaces
yabai -m space 1 --label Messages
yabai -m space 2 --label Discord
yabai -m space 3 --label "Microsoft Teams"
yabai -m space 4 --label "Brave Browser"
yabai -m space 5 --label Music
yabai -m space 6 --label WezTerm

# Rules
yabai -m rule --add app="Messages" space=1
yabai -m rule --add app="Discord" space=2
yabai -m rule --add app="Microsoft Teams" space=3
yabai -m rule --add app="Music" space=4
yabai -m rule --add app="Brave Browser" space=5
yabai -m rule --add app="WezTerm" space=6

#
# global settings
yc "active_window_border_color" "0xff775759"
yc "active_window_opacity" "1.0"
yc "auto_balance" "off"
yc "external_bar" "all:28:0"
yc "focus_follows_mouse" "off"
yc "insert_feedback_color" "0xffd75f5f"
yc "layout" "bsp"
yc "mouse_action1" "move"
yc "mouse_action2" "resize"
yc "mouse_drop_action" "swap"
yc "mouse_follows_focus" "off"
yc "mouse_modifier" "fn"
yc "normal_window_border_color" "0xff555555"
yc "normal_window_opacity" "0.90"
yc "padding" "all:2:2:2:2"
yc "split_ratio" "0.50"
yc "split_type" "auto"
yc "window_animation_duration" "0.0"
yc "window_animation_frame_rate" "120"
yc "window_border" "off"
yc "window_border_blur" "off"
yc "window_border_hidpi" "on"
yc "window_border_radius" "12"
yc "window_border_width" "4"
yc "window_gap" "2"
yc "window_opacity" "off"
yc "window_opacity_duration" "0.0"
yc "window_origin_display" "default"
yc "window_placement" "second_child"
yc "window_shadow" "on"
yc "window_topmost" "off"
yc "window_zoom_persist" "on"

echo "yabai configuration loaded.."
