#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# Spaces
yabai -m space 1 --label Messages
yabai -m space 2 --label Discord
yabai -m space 3 --label Teams
yabai -m space 4 --label Browser
yabai -m space 5 --label Music
yabai -m space 6 --label Terminal

# Rules
yabai -m rule --add app="Messages" space=1
yabai -m rule --add app="Discord" space=2
yabai -m rule --add app="Microsoft Teams" space=3
yabai -m rule --add app="Microsoft Teams Notification" space=3
yabai -m rule --add app="Music" space=4
yabai -m rule --add app="Brave Browser" space=5
yabai -m rule --add app="WezTerm" space=6

#
# global settings
yabai -m config                                 \
    active_window_border_color   0xff775759     \
    active_window_opacity        1.0            \
    auto_balance                 off            \
    external_bar                 all:20:0       \
    padding                      all:2:2:2:2    \
    focus_follows_mouse          off            \
    insert_feedback_color        0xffd75f5f     \
    layout                       bsp            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    mouse_follows_focus          off            \
    mouse_modifier               fn             \
    normal_window_border_color   0xff555555     \
    normal_window_opacity        0.90           \
    split_ratio                  0.50           \
    split_type                   auto           \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_border                off            \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border_radius         12             \
    window_border_width          4              \
    window_gap                   2            \
    window_opacity               off            \
    window_opacity_duration      0.0            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_shadow                on             \
    window_topmost               off            \
    window_zoom_persist          on             \
    echo "yabai configuration loaded.."
