#!/bin/bash

ICON_ON=""
ICON_OFF=""
COLOR_ON="c3e88d"
COLOR_OFF="ff757f"

COLOR="c3e88d"
ICON="${ICON_ON}"

if [[ $(dunstctl get-pause-level) == 0 ]]; then
    ICON=$ICON_ON
    COLOR=$COLOR_ON
else
    ICON=$ICON_OFF
    COLOR=$COLOR_OFF
fi

echo "<span foreground=\"#${COLOR}\">${ICON}</span>"
