-- require('indent-blankline').setup {
--     buftype_exclude = {
--         "nofile",
--         "terminal",
--     },
--     filetype_exclude = {
--         "help",
--         "startify",
--         "aerial",
--         "alpha",
--         "dashboard",
--         "packer",
--         "neogitstatus",
--         "NvimTree",
--         "neo-tree",
--         "Trouble",
--     },
--     context_patterns = {
--         "class",
--         "return",
--         "function",
--         "method",
--         "^if",
--         "^while",
--         "jsx_element",
--         "^for",
--         "^object",
--         "^table",
--         "block",
--         "arguments",
--         "if_statement",
--         "else_clause",
--         "jsx_element",
--         "jsx_self_closing_element",
--         "try_statement",
--         "catch_clause",
--         "import_statement",
--         "operation_type",
--     },
--     show_trailing_blankline_indent = false,
--     use_treesitter = true,
--     char = "▏",
--     context_char = "▏",
--     show_current_context = true,
-- }
require("indent_blankline").setup({
	show_end_of_line = true,
	space_char_blankline = " ",
	show_current_context = true,
	show_current_context_start = false,
	use_treesitter = true,
})

for _, keymap in pairs({
	"zo",
	"zO",
	"zc",
	"zC",
	"za",
	"zA",
	"zv",
	"zx",
	"zX",
	"zm",
	"zM",
	"zr",
	"zR",
}) do
	vim.api.nvim_set_keymap("n", keymap, keymap .. "<CMD>IndentBlanklineRefresh<CR>", { noremap = true, silent = true })
end
