command_timeout = 5000
add_newline = false

format = "[󰣇](bold #74c7ec) $directory$all"
# [╭╴[](bold #74c7ec) ](bold #cba6f7)$all
#
[character] # The name of the module we are configuring is 'character'
# success_symbol = '[󱞪](bold green)'
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❯](bold red)'

[git_branch]
symbol = " "

[kubernetes]
# detect_env_vars = ["HTTPS_PROXY"]
disabled = false
format = "on [$symbol$context](bold $style) "
symbol = "󱃾 "
style = "purple"
contexts = [
    { context_pattern = "aks08-dev-eus", context_alias = "dev (aks08)" },
    { context_pattern = "aks06-dev-eus", context_alias = "qa (aks06)" },
    { context_pattern = "aks04-prod-eus", context_alias = "prod (aks04)" },
    { context_pattern = "local", context_alias = "local" },
]

[env_var.HTTPS_PROXY]
format = "with [ $env_value](#565f89) "

[python]
symbol = " "

