#!/bin/bash

DUNST_TIMEOUT=3   # duration in seconds
DUNST_URGENCY=low # low, normal or critical

if xwininfo -name "teams.microsoft.com is sharing your screen." >/dev/null 2>&1; then
	if ! [ -f "/tmp/i3notify.lock" ]; then
		touch /tmp/i3notify.lock
		notify-send -u ${DUNST_URGENCY} -t ${DUNST_TIMEOUT}000 Dunst "Screen sharing mode activated"
		sleep ${DUNST_TIMEOUT}
		dunstctl set-paused true
		echo "<span foreground=\"#f38ba8\"> </span>"
	else
		echo "<span foreground=\"#f38ba8\"> </span>"
	fi

else
	if [ -f "/tmp/i3notify.lock" ]; then
		rm /tmp/i3notify.lock
		dunstctl set-paused false
		notify-send -u ${DUNST_URGENCY} -t ${DUNST_TIMEOUT}000 Dunst "Screen sharing mode de-activated"
	fi
	echo "<span foreground=\"#b4befe\"> </span>"
fi
