[general]
# import = [
#     "~/.config/alacritty/themes/tokyonight-moon.toml"
# ]
# [keyboard]
# bindings = [
#       { key="J", mods="Alt", chars="\x1bj" },
#   { key="K", mods="Alt", chars="\x1bk" },
#   { key="H", mods="Alt", chars="\x1bh" },
#   { key="L", mods="Alt", chars="\x1bl" }
# ]

[cursor.style]
shape = "Block"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 9.0

[font.glyph_offset]
x = 0
y = 1

[font.bold]
# family = "JetBrainsMonoNL NF"
# family = "HackNerdFontMono"
# family = "BerkeleyMonoTrial"
# family = "CascadiaMono"
family = "SplineSansMono"
style = "Bold"

[font.bold_italic]
# family = "JetBrainsMonoNL NF"
# family = "HackNerdFontMono"
# family = "BerkeleyMonoTrial"
# family = "CascadiaMono"
family = "SplineSansMono"
style = "Bold Italic"

[font.italic]
# family = "JetBrainsMonoNL NF"
# family = "HackNerdFontMono"
# family = "BerkeleyMonoTrial"
# family = "CascadiaMono"
family = "SplineSansMono"
style = "Italic"

[font.normal]
# family = "MonaspaceKrypton"
# family = "BerkeleyMonoTrial"
# family = "JetBrainsMonoNL NF"
# family = "HackNerdFontMono"
# family = "CascadiaMono"
family = "SplineSansMono"
style = "Regular"

[selection]
save_to_clipboard = true

