# Theme

font_size 10.5
disable_ligatures always

# Key Binds
map ctrl+shift+u none
map ctrl+shift+n no_op
map ctrl+cmd+r load_config_file
map ctrl+shift+plus change_font_size current +0.5
map ctrl+shift+minus change_font_size current -0.5
map ctrl+shift+0 change_font_size current 0
map ctrl+shift+k scroll_page_up
map ctrl+shift+j scroll_page_down
map ctrl+cmd+e pipe @screen_scrollback overlay nvim - -c 'set filetype=scrollback' -c 'source ~/.vim/ftplugin/scrollback.vim'


# Visual
# hide_window_decorations titlebar-only
# window_padding 5 5 0 0

# Cursor config
cursor_shape block
cursor_trail 3
cursor_trail_decay 0.05 0.2
shell_integration no-cursor

# Miscellaneous
confirm_os_window_close 0
scrollback_lines 10000
copy_on_select yes
enable_audio_bell no
window_margin_width 0 1 0 0
allow_remote_control yes


disable_ligatures always

# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family=TX-02 style=Light features=+ss02
bold_font        family=TX-02 style=Regular features=+ss02
italic_font     family="Iosevka Fixed" style="Light Extended Italic" 
bold_italic_font family="Iosevka Fixed" style="Medium Extended Italic"
# END_KITTY_FONTS
